line-length = 100 # Longueur maximale des lignes
target-version = "py312" # Version de Python

[lint]
select = ["E", "F", "W", "I", "N", "UP"] # Sélection des règles de linting
ignore = ["E501"] # Ignorer la règle E501, ligne trop longue

[lint.per-file-ignores]
"tests/**" = ["S101"]   # autorise assert dans les tests
